name: Reusable Workflow

on:
  workflow_call:

jobs:
  tf_plan:
    runs-on: ubuntu-latest
    steps:
      - name: TEST Plan
        run: |
          echo "terraform plan running"

  tf_apply:
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) }}
    needs: tf_plan
    runs-on: ubuntu-latest
    steps:
      - name: TEST Apply
        run: |
          echo "terraform apply running"

      - name: Debug Context
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"