name: Reusable Workflow

on:
  workflow_call:

jobs:
  tf_plan:
    runs-on: ubuntu-latest
    steps:
      - name: TEST Plan
        run: |
          echo "terraform plan running"

  tf_apply:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: tf_plan
    runs-on: ubuntu-latest
    steps:
      - name: TEST Apply
        run: |
          echo "terraform apply running"
